"""AgentForge core — stable contracts (ABCs, value types).

Per ADR-0007, this package's public surface is the framework's locked
contract layer. Adding a method to an ABC is a major version bump.

This module re-exports every public symbol so consumers can import
from `agentforge_core` directly. Submodules (`agentforge_core.contracts`,
`agentforge_core.values`, `agentforge_core.production`) remain part of
the public surface for granular imports.
"""

from __future__ import annotations

# Version is sourced from the installed distribution metadata so it can
# never drift from pyproject.toml (bug-024).
from importlib.metadata import PackageNotFoundError as _PkgNotFound
from importlib.metadata import version as _dist_version

from agentforge_core.config import (
    AgentConfig,
    AgentForgeConfig,
    BudgetConfig,
    EvaluatorEntry,
    GraphModuleConfig,
    LoggingConfig,
    MemoryModuleConfig,
    ModuleEntry,
    ModulesConfig,
    ObservabilityEntry,
    OutputConfig,
    ProviderConfig,
    RerankerEntry,
    RetrievalConfig,
    RetrieverModuleConfig,
    load_config,
    parse_overrides,
)
from agentforge_core.contracts import (
    EmbeddingClient,
    EvalResult,
    Evaluator,
    Finding,
    FindingRenderer,
    GraphStore,
    LLMClient,
    MemoryStore,
    Migration,
    MigrationChecksumError,
    MigrationStatus,
    Migrator,
    ReasoningStrategy,
    Reranker,
    Tool,
    VectorStore,
    validate_tool_name,
)
from agentforge_core.migrations import discover_migrations
from agentforge_core.observability import SCOPE_NAME as OBSERVABILITY_SCOPE_NAME
from agentforge_core.observability import get_tracer
from agentforge_core.production import (
    AgentForgeError,
    AuthenticationError,
    BudgetExceeded,
    BudgetPolicy,
    CapabilityNotSupported,
    GuardrailViolation,
    JsonFormatter,
    ModelNotFoundError,
    ModuleError,
    ProviderError,
    RateLimitError,
    RunContext,
    RunIdFilter,
    ServiceError,
    TimeoutError,
    ToolNameInvalidError,
    bind_run,
    current_run,
    install_json_formatter,
    install_run_id_filter,
    new_run,
    reset_run,
    uninstall_json_formatter,
    uninstall_run_id_filter,
)

# Imported from the submodule directly (not via production/__init__)
# to avoid a circular import — see the comment in production/__init__.py
# for the chain. This import runs *after* production finishes, so
# LLMClient is already available.
from agentforge_core.production.fallback import FallbackChain
from agentforge_core.resolver import (
    Resolver,
    discover_entry_points,
    parse_model_string,
    register,
    register_embedding_provider,
    register_provider,
    reset_discovery,
)
from agentforge_core.values import (
    AgentState,
    AppliedEnvVar,
    AppliedManifest,
    AppliedTemplate,
    Claim,
    EmbeddingResponse,
    EnvVarEntry,
    FinishReason,
    GraphEdge,
    GraphNode,
    GraphPattern,
    GraphSegment,
    LLMResponse,
    Manifest,
    Message,
    MessageRole,
    ModuleInfo,
    Path,
    RunResult,
    Step,
    StepKind,
    StopReason,
    StreamChunk,
    StreamChunkKind,
    TemplateFile,
    TokenUsage,
    ToolCall,
    ToolSpec,
    VectorItem,
    VectorMatch,
)

try:
    __version__ = _dist_version("agentforge-core")
except _PkgNotFound:  # pragma: no cover - source tree without installed metadata
    __version__ = "0.0.0+unknown"

__all__ = [
    "OBSERVABILITY_SCOPE_NAME",
    "AgentConfig",
    "AgentForgeConfig",
    "AgentForgeError",
    "AgentState",
    "AppliedEnvVar",
    "AppliedManifest",
    "AppliedTemplate",
    "AuthenticationError",
    "BudgetConfig",
    "BudgetExceeded",
    "BudgetPolicy",
    "CapabilityNotSupported",
    "Claim",
    "EmbeddingClient",
    "EmbeddingResponse",
    "EnvVarEntry",
    "EvalResult",
    "Evaluator",
    "EvaluatorEntry",
    "FallbackChain",
    "Finding",
    "FindingRenderer",
    "FinishReason",
    "GraphEdge",
    "GraphModuleConfig",
    "GraphNode",
    "GraphPattern",
    "GraphSegment",
    "GraphStore",
    "GuardrailViolation",
    "JsonFormatter",
    "LLMClient",
    "LLMResponse",
    "LoggingConfig",
    "Manifest",
    "MemoryModuleConfig",
    "MemoryStore",
    "Message",
    "MessageRole",
    "Migration",
    "MigrationChecksumError",
    "MigrationStatus",
    "Migrator",
    "ModelNotFoundError",
    "ModuleEntry",
    "ModuleError",
    "ModuleInfo",
    "ModulesConfig",
    "ObservabilityEntry",
    "OutputConfig",
    "Path",
    "ProviderConfig",
    "ProviderError",
    "RateLimitError",
    "ReasoningStrategy",
    "Reranker",
    "RerankerEntry",
    "Resolver",
    "RetrievalConfig",
    "RetrieverModuleConfig",
    "RunContext",
    "RunIdFilter",
    "RunResult",
    "ServiceError",
    "Step",
    "StepKind",
    "StopReason",
    "StreamChunk",
    "StreamChunkKind",
    "TemplateFile",
    "TimeoutError",
    "TokenUsage",
    "Tool",
    "ToolCall",
    "ToolNameInvalidError",
    "ToolSpec",
    "VectorItem",
    "VectorMatch",
    "VectorStore",
    "__version__",
    "bind_run",
    "current_run",
    "discover_entry_points",
    "discover_migrations",
    "get_tracer",
    "install_json_formatter",
    "install_run_id_filter",
    "load_config",
    "new_run",
    "parse_model_string",
    "parse_overrides",
    "register",
    "register_embedding_provider",
    "register_provider",
    "reset_discovery",
    "reset_run",
    "uninstall_json_formatter",
    "uninstall_run_id_filter",
    "validate_tool_name",
]
